// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDss4ySMllxzzfRB4BDDjHNynZKxHX5FXg',
    appId: '1:78837080015:android:57d177d541c197230b7cba',
    messagingSenderId: '78837080015',
    projectId: 'medexer-mobile',
    storageBucket: 'medexer-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4JOtoNSaVJcy25KipEHKecw_NPCGdt2g',
    appId: '1:78837080015:ios:6b4dccea705c416f0b7cba',
    messagingSenderId: '78837080015',
    projectId: 'medexer-mobile',
    storageBucket: 'medexer-mobile.firebasestorage.app',
    androidClientId: '78837080015-aaes4211t3l1glglbpjviishca6jg186.apps.googleusercontent.com',
    iosClientId: '78837080015-o2hpvlbt1j912u3159ms31vv2mg79c39.apps.googleusercontent.com',
    iosBundleId: 'com.medexer.medexer',
  );

}